# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Deployment

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm run build
    - name: Remove old build from remote server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USR }}
        password: ${{ secrets.REMOTE_PWD }}
        port: 22
        script: find ${{ secrets.REMOTE_PATH }} -type f,d ! -iname ".*" -not -path ${{ secrets.REMOTE_PATH }} -delete
    - name: Deploy build to remote server
      uses: Creepios/sftp-action@v1.0.3
      with:
        host: ${{ secrets.REMOTE_HOST }}
        port: 22
        username: ${{ secrets.REMOTE_USR }}
        password: ${{ secrets.REMOTE_PWD }}
        localPath: ${{ secrets.BUILD_PATH }}
        remotePath: ${{ secrets.REMOTE_PATH }}
